language: python

python:
    - "2.7"

install:
    - sudo apt-get install libhdf5-serial-dev
    - pip install -r requirements.txt

# command to run tests
script:
    - cd unittest
    - python -m unittest discover -b