language: python

sudo: false
dist: trusty

python:
  - "2.7"

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy h5py matplotlib phonopy anaconda-client anaconda-build
    - pwd
    - python setup.py install

#    - pip install -r requirements.txt"

# command to run tests
# script: pytest